### ISSUE TITLE
Code snippet

### ISSUE THREAD

**Issue by arunmullur** [austinmh12/pybeamer#2]
![image](https://github.com/user-attachments/assets/6682cc6f-90c7-4189-a079-2995a82ee06c)

Is there a problem with URL? I am accessing swagger, does it have to be local client?
Im just trying out with the examples provided.

**Comment by austinmh12** [comment]
The API URL is just the base URL you'd use to go to the website. The Swagger URL is for using the online API endpoint viewer; if you remove everything from the `/v3` onward, you should get the expected results.

**Comment by arunmullur** [comment]
Traceback (most recent call last):
  File "c:\Users\emp-102488\Codebeamer\pybeamerapi.py", line 8, in <module>
    projects = codebeamer.get_projects()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\emp-102488\Codebeamer\pybeamer\client.py", line 23, in get_projects
    return [Project(**p, client=self._client) for p in self._client.get('projects')]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\emp-102488\Codebeamer\pybeamer\client.py", line 23, in <listcomp>
    return [Project(**p, client=self._client) for p in self._client.get('projects')]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pybeamer.projects.Project() argument after ** must be a mapping, not int 

No I am still getting the same error. I just want to list all items in a tracker mentioned in the tracker id and project 26.

**Comment by austinmh12** [comment]
What do you get if you run `print(codebeamer._client.get('projects')`?

**Comment by arunmullur** [comment]
If I run this, Im getting the html page details of codebeamer, many lines appear as text.

![image](https://github.com/user-attachments/assets/23019874-e05c-4feb-a89f-e7b3e944a65a)

**Comment by austinmh12** [comment]
Your URL is still incorrect then, you should be seeing something along the lines of this:
```json
[{'id': 3, 'name': 'Standards', 'type': 'ProjectReference'}, {'id': 7, 'name': 'codebeamer Documentation', 'type': 'ProjectReference'}]
```

**Comment by arunmullur** [comment]
Thanks for the headsup, its just a starters problem for me, im really not able to understand what the problem is with URL, 
![image](https://github.com/user-attachments/assets/f680c33a-4dae-4671-b553-fcbe652d04b8)
 can u please look into it?

**Comment by austinmh12** [comment]
If `https://codebeamer.com/cb/login.spr` is where you go in a browser to login, then the `Codebeamer` object URL param would be `https://codebeamer.com`, I don't have a Codebeamer account on the main cloud website so I can't test this at the moment.

**Comment by arunmullur** [comment]
When I use the URL that u mentioned, in the error message it is trying to add  "........cb/api/v3/projects" this part by it self.

**Comment by austinmh12** [comment]
Can you go to the swagger UI and try running through the GET /Projects endpoint there and post a screenshot of that? The `cb/api/v3` gets added because that's the default `api_root` parameter, and the `projects` is the API endpoint.
![image](https://github.com/user-attachments/assets/0286f11a-bae3-4bbf-8ea6-2cb359b72d23)

**Comment by arunmullur** [comment]
In my case its a bit different,
![image](https://github.com/user-attachments/assets/09c4950e-5097-4396-9ab9-0fe4cefc7e77)

**Comment by austinmh12** [comment]
Ah okay, the below should work for you then:
```python
from pybeamer import Codebeamer

codebeamer = Codebeamer(
    url = 'https://codebeamer.com',
    username = 'xxxxx',
    password='xxxxx',
    api_root='api/v3'
)
```

**Comment by austinmh12** [comment]
I pushed an update that fixes the multiple values for `api_root` so if you grab the latest it should prevent that error.

**Comment by arunmullur** [comment]
A fix to add Api_root worked. Will u be adding more REST API operations or examples here? 
For example: copying hundreds of items from one tracker to another. Or shall I try the usecase myself?

**Comment by austinmh12** [comment]
I do plan on adding more of the rest api endpoints that are listed in the Swagger documentation (or at least all the ones mentioned in the ReadMe). As for the examples, I plan on making more robust examples once I restructure this library to a more proper and easier to install version.

**Comment by arunmullur** [comment]
That would be great, accessing the history of an tracker item and implementation examples of more usecases, it would be helpful. As of now  I have to struggle a bit :-)
